#include "main_mech_interaction.dm"
#include "mech_control.dm"
#include "mech_interaction.dm"
#include "mech_fists\attack.dm"
#include "pilot.dm"

//Обычные взаимодействия
#include "just_interaction\emag_act.dm"
#include "just_interaction\id_card_interaction.dm"
//Взаимодействия обслуживания
#include "maint_interaction\coil_repair.dm"
#include "maint_interaction\customisation.dm"
#include "maint_interaction\deinstall_cell.dm"
#include "maint_interaction\deinstall_equipment.dm"
#include "maint_interaction\force_hatch.dm"
#include "maint_interaction\install_cell.dm"
#include "maint_interaction\install_equipment.dm"
#include "maint_interaction\material_repair.dm"
#include "maint_interaction\mech_bolts.dm"
#include "maint_interaction\equipment_repair.dm"
#include "maint_interaction\paint.dm"
#include "maint_interaction\start_dismantle_mech.dm"
#include "maint_interaction\welder_repair.dm"
//ещё какая-то хуйня
#include "maint_interaction\mech_construction.dm"
#include "maint_interaction\modules_system.dm"
