/singleton/cultural_info/culture/diona
	language = LANGUAGE_ROOTLOCAL
	additional_langs = list(LANGUAGE_ROOTGLOBAL)
	secondary_langs = list(
		LANGUAGE_HUMAN_EURO,
		LANGUAGE_SPACER,
		LANGUAGE_HUMAN_CHINESE,
		LANGUAGE_HUMAN_ARABIC,
		LANGUAGE_HUMAN_INDIAN,
		LANGUAGE_HUMAN_IBERIAN,
		LANGUAGE_HUMAN_RUSSIAN,
		LANGUAGE_HUMAN_SELENIAN,
		LANGUAGE_UNATHI_SINTA,
		LANGUAGE_SKRELLIAN,
		LANGUAGE_SIIK_MAAS,
		LANGUAGE_RESOMI
	)
