#undef COLOR_ASCENT_PURPLE
#undef MANTIDIFY

// Ascent culture.
#undef CULTURE_ASCENT
#undef HOME_SYSTEM_KHARMAANI
#undef FACTION_ASCENT_GYNE
#undef FACTION_ASCENT_ALATE
#undef FACTION_ASCENT_SERPENTID
#undef RELIGION_KHARMAANI

//Languages
#undef LANGUAGE_MANTID_NONVOCAL
#undef LANGUAGE_MANTID_VOCAL
#undef LANGUAGE_MANTID_BROADCAST

//Species
#undef SPECIES_MONARCH_WORKER
#undef SPECIES_MONARCH_QUEEN
#undef SPECIES_MANTID_ALATE
#undef SPECIES_MANTID_GYNE
#undef ALL_ASCENT_SPECIES
