#define INCAPACITATION_RESTING FLAG_08

// Новый флаг: что действительно блокирует действия
#define INCAPACITATION_ACTION_BLOCKED (INCAPACITATION_STUNNED | INCAPACITATION_KNOCKOUT | INCAPACITATION_RESTRAINED | INCAPACITATION_BUCKLED_FULLY)

// Флаг для проверки только положения тела
#define INCAPACITATION_POSITION (INCAPACITATION_RESTING | INCAPACITATION_BUCKLED_PARTIALLY | INCAPACITATION_BUCKLED_FULLY | INCAPACITATION_FORCELYING)
