/datum/species/tajaran
	extended_cultural_info = list(
		TAG_FACTION = list(
			FACTION_NANOTRASEN,
			FACTION_FREETRADE,
			FACTION_HEPHAESTUS,
			FACTION_PCRC,
			FACTION_SAARE,
			FACTION_DAIS,
			FACTION_ZENG_HU,
			FACTION_WARD_TAKAHASHI,
			FACTION_GRAYSON,
			FACTION_AERTHER,
			FACTION_MAJOR_BILL,
			FACTION_FOCAL_POINT,
			FACTION_XION,
			FACTION_VEY_MED,
			FACTION_BISHOP,
			FACTION_ZPCI,
			FACTION_SEPTENERGO
		)
	)
