name: Cancel

permissions:
  contents: read

on:
  push:
    branches:
      - dev

# NB: We can discover workflow IDs for this job at https://api.github.com/repos/ORG/REPO/actions/workflows
jobs:
  cancel:
    name: 'Cancel Redundant Builds'
    permissions:
      actions: write # required to cancel other actions
    runs-on: ubuntu-22.04
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@d07a454dad7609a92316b57b23c9ccfd4f59af66
        with:
          workflow_id: 3545321
          access_token: ${{ github.token }}
